### ISSUE TITLE
Use "helm find file" instead of "helm completion at point"

### ISSUE THREAD

**Issue by fbob** [riscy/shx-for-emacs#22]
I'm using helm on spacemacs.
Is it possible to use `helm find file at point` instead of `helm completion at point` when using `ls` or `cd` commands at the prompt ?  
` helm find file at point` is used for me when I want to open a file or directory with RET when arrowing up to it.
The  `helm find file at point` is much more user friendly.

**Comment by riscy** [comment]
I think this might be because arrowing up and hitting RET on a file will run `find-file-at-point` (with is part of shx's keybindings).  I think helm advises that function but I'm not sure (ivy user here 😁).

But TAB-completing at the prompt when typing cd or ls is probably coming from company-mode or similar -- shx has no keybinding to cover TAB at the moment at least.

**Comment by fbob** [comment]
Ok many thanks for the advice, I will look in that direction :)
... and congratulations for shx it is very useful, thank you  !

**Comment by riscy** [comment]
I'll close this one now, but thank you very much for the feedback and kind words. :)
